### ISSUE TITLE
TypeError: Cannot read property 'dc' of undefined

### ISSUE THREAD

**Issue by Bugari** [sidorares/node-vim-debugger#30]
I installed `vimdebug@0.2.1`, everything seems fine, I start vim, type :nbs, one more gutter line is added,  but right after I press C-p, gutter line dissapears, and node-vim-inspector is closed, with stacktrace:

    start vim with "vim -nb" command or type :nbs within vim
    > 
    /usr/local/lib/node_modules/vimdebug/node_modules/tmp/lib/tmp.js:260
      throw err;
            ^
    TypeError: Cannot read property 'dc' of undefined
        at /usr/local/lib/node_modules/vimdebug/lib/vim-connection.js:94:22
        at VimClient.eventHandlers.keyAtPos (/usr/local/lib/node_modules/vimdebug/node_modules/vim-netbeans/lib/vim-client.js:385:5)
        at VimClient._processEvent (/usr/local/lib/node_modules/vimdebug/node_modules/vim-netbeans/lib/vim-client.js:298:23)
        at VimClient._onMessage (/usr/local/lib/node_modules/vimdebug/node_modules/vim-netbeans/lib/vim-client.js:239:9)
        at Array.forEach (native)
        at VimClient._onData (/usr/local/lib/node_modules/vimdebug/node_modules/vim-netbeans/lib/vim-client.js:220:11)
        at Socket.EventEmitter.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:746:14)
        at Socket.EventEmitter.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:408:10)

**Comment by vicendominguez** [comment]
is this project alive?

I can confirm this "error" and the workaround doesn't work for me. 

Info: node 0.10.29 + MacOSX 10.9.

vim-inspector and vim -nb looks not to be connected: all variables undefined, the cursor doesnot jump and setting breakpoints breaks the inspector with that error message.

I have checked the correct order of the commands a lot of times and they are ok.

Ideas?

**Comment by sidorares** [comment]
@vicendominguez  kind of alive, I'm keeping an eye on it but don't have a lot of free time right now.

**Comment by vicendominguez** [comment]
@sidorares at least thanks for answering... :+1:

**Comment by zeeshanjan82** [comment]
I am also facing the same issue as @Bugari when I using ctrl+p the I get this error. After I use :nbs command I am starting from the first line of server.js and then I need to set a breakpoint on some other .js file which is called at a later stage as a process of booting up of the node.js service. Is there any way to set a breakpoint on any file I want.

**Comment by sidorares** [comment]
not at the moment @zeeshanjan82 , right now you only can do if you in the buffer associated with a script ( e.i you navigated to this buffer by stepping in debugger or going up/down stack )

It's relatively easy to implement - if there is no script associated with buffer, save position + file name to list of pending breakpoints and when script is compiled set actual breakpoint

**Comment by sidorares** [comment]
hi @zeeshanjan82 - please try v1.0.0
Sourcemaps are not yet supported for pending breakpoints but for js files location should be correct
