### ISSUE TITLE
All variables are undefined

### ISSUE THREAD

**Issue by shenron** [sidorares/node-vim-debugger#33]
I can print variable only with:
console.log(myVar);
And the log appear in node --debug-brk console.

When I insert myVar in node-vim-inspector I only see undefined ...

I try in my OSX and Gnu / Linux, I have the same problem.

**Comment by sidorares** [comment]
can't reproduce. Does it happen on any script? I just tried with examples/qqq.js and variables displayed as expected. Can you record a screencast?
