### ISSUE TITLE
the keys doesn't work

### ISSUE THREAD

**Issue by nik-kor** [sidorares/node-vim-debugger#35]
Hi!

It seems that there is no any effect when pushing keys, e.g. 'C-c'.
I tried to use the latest master - the same result. I tried to remap some keys by .vimdebugrc or by cli options - the same result.

What am i doing wrong?

**Comment by nik-kor** [comment]
I made some experiments and found that command `nnoremap : ;` in my .vimrc file breaks nb server.
So it didn't get any events. I really don't know why.)

But now it's ok. Anyway your project is great!

**Comment by sidorares** [comment]
Thanks! I have tons of features I'd like to add here but don't have enough time. If you would like to hack on the project - ping me at any time and I'll try to help
