### ISSUE TITLE
When source file found in existing buffer focus it; don't open duplicate in new buffer.

### ISSUE THREAD

**Issue by tecfu** [sidorares/node-vim-debugger#43]
Great plugin - thanks!

My work flow goes like this: I'll be editing a source file within Vim (myprogram.js) and run node-vim-inspector via a Vim terminal emulator plugin. 

I use Shougo/Vimshell and call :VimShellPop so that I can see the console in a horizontal split within my current window. 

```
node-vim-inspector myprogram.js
```

Now I run :nbs in Vim and the debugger starts working. But instead of stepping through the 'myprogram.js' file in the current buffer (as expected), node-vim-inspector opens a new buffer with 'myprogram.js' - leaving me with multiple buffers having the same source. 

Now, I can see this might be a conflict if we have unsaved changes in an existing buffer with the source file - and then try to step through code that doesn't correspond. But we could check for diffs and assuming the files match proceed. 

Thoughts?

**Comment by sidorares** [comment]
hi @tecfu 

I'm not a big expert in vim, I wish this library integrate more closely with vim but at the moment the only way it interacts is by sending commands to netbeans server ( which vim starts when you type `:nbs` )

For 'open new buffer + go to location'  it sends 'editFile' command ([using vim-netbeans client](https://github.com/clehner/node-vim-netbeans/blob/050df30bab811b9917fe9d8b6a96d264193ee16b/lib/vim-buffer.js#L78) )

I'm afraid that could be limitation of netbeans protocol

**Comment by tecfu** [comment]
Thanks for your speedy reply. You are right about this - the code that needs to be changed is in vim-netbeans exactly [here](https://github.com/clehner/node-vim-netbeans/blob/master/lib/vim-client.js#L407).

**Comment by sidorares** [comment]
I can probably handle this on my side: maintain a mapping between filename / bufferId and re-use buffer if it already opened (not sure if I already do this or not)

but that's not exactly your issue: you have buffer opened by non-netbeans means (probably manually) and netbeans protocol does not allow to see list of opened buffers

**Comment by tecfu** [comment]
You are absolutely right about this. 

I'm left thinking that the only solution is to fork and rewrite your plugin to work with neovim and use [the neovim rpc library for nodejs](https://github.com/fritzy/node-neovim).

Its another project that I don't have time for but will add to my long term list. 

As far as your plugin goes, do you actually use this? Maybe I am missing something in my workflow or simply obtuse...but to me it seems really burdensome to keep opening redundant tabs everytime I want to run the debugger.

**Comment by tecfu** [comment]
Didn't mean to reopen.

**Comment by sidorares** [comment]
yeah, I did a bit of research and put some notes at #40 but didn't have much time to progress

**Comment by sidorares** [comment]
> As far as your plugin goes, do you actually use this? Maybe I am missing something in my workflow or simply obtuse...but to me it seems really burdensome to keep opening redundant tabs everytime I want to run the debugger.

not really, that was more like experimental project. I use atom most of the time and vim occasionaly when I don't want to leave command line, and for debugging prefer to use node built-in command line debugger
