### ISSUE TITLE
Integration with the new --inspect option

### ISSUE THREAD

**Issue by Climax777** [sidorares/node-vim-debugger#44]
Hi

The --debug flag has been deprecated in favor of the new --inspect option, though node-vim-inspector doesn't work when using the new flag.

**Comment by sidorares** [comment]
see #38 

basically, debugging protocol exposed with `--inspect` is completely different

**Comment by Climax777** [comment]
I understand, thanks though...

**Comment by T-vK** [comment]
@Climax777 I'm currently using a different vim plugin which does support `--inspect`. Maybe this helps... https://github.com/eliba2/vim-node-inspect
